---
  environment: production
  address: 127.0.0.1
  port: 9300
  pid: prod.pid
  rackup: conf/prod.ru
  log: log/prod.log
  max_conns: 1024
  timeout: 30
  max_persistent_conns: 1024
  daemonize: true
